apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lenses-ingress
  namespace: lenses
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lenses-hq
            port:
              number: 80
