apiVersion: v1
kind: Service
metadata:
  name: demo-kafka
  namespace: kafka
  labels:
    app: demo-kafka
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: schema-reg
  selector:
    app: demo-kafka
