# Kafka Bitnami Helm chart values for Minikube with KRaft mode

## Global settings
global:
  storageClass: "standard" # Use default Minikube storage class

## Enable KRaft mode and disable Zookeeper
kraft:
  enabled: true
  controllerQuorumVoters: "0@kafka-controller-0.kafka-controller-headless.kafka.svc.cluster.local:9093"

# Disable Zookeeper since we're using KRaft
zookeeper:
  enabled: false

## Kafka specific configurations
replicaCount: 1 # Single broker for Minikube setup

# Resource limits suitable for Minikube
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Reduced persistence size for Minikube
persistence:
  enabled: true
  size: 2Gi # Reduced storage size as requested

# Networking configuration for Minikube
service:
  type: NodePort # Makes Kafka accessible from outside Minikube
  nodePorts:
    client: 31090
    external: 31091

# Default listeners configuration for KRaft mode
listeners:
  client:
    name: PLAINTEXT
    protocol: PLAINTEXT
    containerPort: 9092
  controller:
    name: CONTROLLER
    protocol: PLAINTEXT
    containerPort: 9093
  interbroker:
    name: INTERNAL
    protocol: PLAINTEXT
    containerPort: 9094

# Disable authentication for simplicity in dev environment
auth:
  clientProtocol: plaintext
  interBrokerProtocol: plaintext
  sasl:
    enabled: false
    jaas:
      clientUsers: []
      interBrokerUser: ""
  tls:
    enabled: false
  zookeeper:
    user: ""
    password: ""

# Configuration suitable for development
configurationOverrides:
  "offsets.topic.replication.factor": 1 # Set to 1 for single-broker
  "transaction.state.log.replication.factor": 1 # Set to 1 for single-broker
  "transaction.state.log.min.isr": 1 # Set to 1 for single-broker
  "log.retention.hours": 24 # Reduced log retention for dev environment
  "num.partitions": 3 # Default number of partitions for topics
  "security.inter.broker.protocol": PLAINTEXT
  "sasl.enabled.mechanisms": ""
  "sasl.mechanism.inter.broker.protocol": PLAINTEXT
  "allow.everyone.if.no.acl.found": "true"

# Disable JMX exporter for simplicity
metrics:
  jmx:
    enabled: false
  kafka:
    enabled: false

# Disable auto-creation of topics
allowAutoTopicCreation: true
